version: "3.9"
services:
  mysql:
    ports:
      - "3306:3306"
    image: "mysql:8.0.32"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e2e_tests_example
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot",
        ]
      timeout: 20s
      retries: 10
  migrator:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.migrator
    environment:
      - MIGRATOR_ENV=e2e
  web:
    depends_on:
      migrator:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:80"
      - "11000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=e2e
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/app.pfx
    volumes:
      - ./tests/e2e/https:/https:ro
    entrypoint: "/bin/bash -c 'cp /https/ca.cert.crt /usr/local/share/ca-certificates/ca.cert.crt && chmod 644 /usr/local/share/ca-certificates/ca.cert.crt && update-ca-certificates && dotnet BackendApp.Web.dll'"
